- title: Fast upload.
  photo: drag
  buttons:
    - text: Guide
      href: https://time.dreamnet.tech/docs/guide
  summary: |-
    You can **drag and drop** photos and folders into the application.
  content: |-
    Upload instantly by **dragging and dropping** photos, folders and even web addresses to the application. It doesn't matter if you are watching another photo, changing the settings or playing, this works everywhere.

- title: What are the best photos?
  photo: tips
  buttons:
    - text: More tips
      href: https://time.dreamnet.tech/docs/guide/photos
  summary: |-
    Get the best results with photos that only have one person and as few clothes as possible ...
  content: |-
    - Only one person in the photo.
    - Less clothing as possible. Bikinis work better.
    - Body facing the camera.
    - Person standing in a straight position without crossing arms or legs.
    - Body visible and unobstructed.

- title: Settings.
  photo: settings
  buttons:
    - text: Go to settings
      href: /settings
  summary: |-
    DreamTime is widely customizable, visit the settings to find all the options.
  content: |-
    One of the advantages of DreamTime is its wide variety of options and customization that you can set for your convenience.

    Some of these options are important for good results, do not stay with the same options always!
