- id: user
  label: User ID.
  description: Anonymous identification for your session.
  input: input

- id: app.disableHardwareAcceleration
  label: Hardware acceleration.
  description: Can improve performance on some devices. (Requires restart to take effect)
  input: select
  options:
    - label: Disabled
      value: true
    - label: Enabled
      value: false

- id: app.uploadMode
  label: Upload mode.
  description: The uploaded photos will be added to the selected section.
  input: select
  options:
    - label: Pending
      value: none
    - label: Pending -> Preferences
      value: go-preferences
    - label: Queue
      value: add-queue

- id: app.duplicates
  label: Allow duplicates.
  description: Allow the upload of the same photo multiple times.
  input: select
  options:
    - label: Enabled
      value: true
    - label: Disabled
      value: false

- id: app.queuePosition
  label: Queue position.
  description: Change the position of the queue bar.
  input: select
  options:
    - label: Right
      value: right
    - label: Left
      value: left

- id: app.showAds
  label: Show Ads.
  description: Show ads that might interest you and support the development of DreamTime.
  input: select
  options:
    - label: Enabled
      value: true
    - label: Disabled
      value: false

- id: app.showTips
  label: Show Tips.
  description: Show help tips.
  input: select
  options:
    - label: Enabled
      value: true
    - label: Disabled
      value: false

- id: preferences.advanced.device
  label: Device.
  description: GPU is faster but depends on the device VRAM. CPU is slower but uses system RAM.
  input: select
  options:
    - label: CPU
      value: CPU
    - label: NVIDIA GPU
      value: GPU

- id: processing.gpus
  label: GPU.
  description: Graphics card to use.

- id: processing.cores
  label: CPU Cores.
  description: "Using more cores increases the nudification speed for GIFs and videos but decrease stability. Recommended: 1"
  input: input

- id: processing.usePython
  label: Use Python.
  description: Use Python to start the nudification algorithm. Enable this only if you know what are you doing.
  input: select
  options:
    - label: Enabled
      value: true
    - label: Disabled
      value: false

- id: preferences.mode
  label: Preferences Mode.
  description: Complexity of options for the photo.
  input: select
  options:
    - label: Minimal
      value: 0
    - label: Simple
      value: 1
    - label: Normal
      value: 2
    - label: Advanced (Custom masks)
      value: 3
  animated-options:
    - label: Minimal
      value: 0
    - label: Simple
      value: 1
    - label: Normal
      value: 2

- id: preferences.advanced.scaleMode
  label: Scale method.
  description: Indicates how the photo will be scaled.
  input: select
  options:
    - label: None
      value: none
    - label: "Automatic Resize"
      value: auto-rescale
    - label: "Automatic Padding"
      value: auto-resize
    - label: "Automatic Crop"
      value: auto-resize-crop
    - label: Overlay
      value: overlay
    - label: Crop
      value: cropjs
    - label: Color Padding
      value: padding
  animated-options:
    - label: None
      value: none
    - label: "Automatic Resize"
      value: auto-rescale
    - label: "Automatic Padding"
      value: auto-resize
    - label: "Automatic Crop"
      value: auto-resize-crop

- id: preferences.body.executions
  label: Runs.
  description: Number of times the photo will be nudified.
  input: input
  attrs:
    type: number
    min: 1

- id: preferences.body.randomize
  label: Randomize.
  description: Set random body preferences at each run.
  input: select
  options:
    - label: Enabled
      value: true
    - label: Disabled
      value: false

- id: preferences.body.progressive.enabled
  label: Progressive.
  description: Body preferences increase.
  input: select
  options:
    - label: Enabled
      value: true
    - label: Disabled
      value: false

- id: preferences.body.progressive.rate
  label: Progressive rate.
  description: Rate.
  input: input

- id: preferences.advanced.useColorPaddingStrip
  label: Color Padding Removal.
  description: Automatically remove the color padding mask.
  input: select
  options:
    - label: Enabled
      value: true
    - label: Disabled
      value: false

- id: preferences.advanced.useColorTransfer
  label: Color Transfer.
  description: Use a experimental algorithm to recover the original colors of the photo.
  input: select
  options:
    - label: Enabled
      value: true
    - label: Disabled
      value: false

- id: preferences.advanced.imageSize
  label: Image size.
  description: Photo scale size. Larger sizes requires more RAM and can produce less satisfactory results.
  input: select
  options:
    - label: 256x256
      value: 256
    - label: 512x512
      value: 512
    - label: 768x768
      value: 768
    - label: 1024x1024
      value: 1024
    - label: 1280x1280
      value: 1280

- id: preferences.advanced.compress
  label: Compression level.
  description: Compress the photo before nudification to save RAM.
  input: select
  options:
    - label: Disabled
      value: 0
    - label: Low
      value: 25
    - label: Medium
      value: 50
    - label: High
      value: 75

- id: preferences.advanced.waifu.enabled
  label: Waifu2X.
  description: Use an algorithm to upscale & denoise the nudified photo.
  input: select
  options:
    - label: Enabled
      value: true
    - label: Disabled
      value: false

- id: preferences.advanced.waifu.scale
  label: Upscale ratio.
  description:
  input: select
  options:
    - label: 2x
      value: 2
    - label: 3x
      value: 3
    - label: 4x
      value: 4

- id: preferences.advanced.waifu.denoise
  label: Denoise level.
  description:
  input: select
  options:
    - label: Disabled
      value: 0
    - label: Low
      value: 1
    - label: Medium
      value: 2
    - label: High
      value: 3

- id: preferences.advanced.waifu.tta
  label: TTA level.
  description: Can increase the quality of the upscale but it will take more time.
  input: select
  options:
    - label: Disabled
      value: 0
    - label: Low
      value: 2
    - label: Medium
      value: 4
    - label: High
      value: 8

- id: preferences.advanced.waifu.arch
  label: Model.
  description: Each model can give different results in each photo.
  input: select
  options:
    - label: VGG7
      value: 0
    - label: UpConv7
      value: 1
    - label: ResNet10
      value: 2
    - label: UpResNet10
      value: 3

- id: notifications.run
  label: Every run.
  description: Notify when the program is not in the foreground and a single run have finished.
  input: select
  options:
    - label: Enabled
      value: true
    - label: Disabled
      value: false

- id: notifications.allRuns
  label: Every dream.
  description: Notify when the program is not in the foreground and all the runs have finished.
  input: select
  options:
    - label: Enabled
      value: true
    - label: Disabled
      value: false

- id: notifications.update
  label: Update available.
  description: Notify when there is a new version of DreamTime, DreamPower or the checkpoints.
  input: select
  options:
    - label: Enabled
      value: true
    - label: Disabled
      value: false

- id: folders.cli
  label: DreamPower.
  description: Nudification algorithm.

- id: folders.waifu
  label: Waifu2X.
  description: Upscale and denoise algorithm.

- id: folders.models
  label: Models.
  description: Final nudes.

- id: folders.cropped
  label: Temporal.
  description: Temporary files for processing.

- id: telemetry.bugs
  label: Error report.
  description: Allow to report errors automatically.
  input: select
  options:
    - label: Enabled
      value: true
    - label: Disabled
      value: false

- id: telemetry.dom
  label: Session tracking.
  description: Allow to send information about how you use the application. (No sensitive information or photos will be sent)
  input: select
  options:
    - label: Enabled
      value: true
    - label: Disabled
      value: false
