name: CI/CD

on:
  push:
    branches:
      - canary
      - feature/*
      - hotfix/*
    tags:
      - v*

  pull_request:
    branches:
      - canary
    paths:
      - .github/workflows/*
      - src/*

jobs:
  build:
    name: Build (${{ matrix.os-short }})
    runs-on: ${{ matrix.os }}

    # Strategy
    # or a.k.a variables for multiple platforms
    # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstrategy
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest

        include:
          - os: ubuntu-latest # Ubuntu
            os-short: ubuntu
            os-extension: snap
          - os: windows-latest # Windows
            os-short: windows
            os-extension: exe
          - os: macOS-latest # macOS
            os-short: macos
            os-extension: dmg

    steps:
      - name: Dump GitHub context
        if: false
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        continue-on-error: true

      - name: Dump runner context
        if: false
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
        continue-on-error: true

      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Use Yarn
        run: npm install -g yarn

      - name: Setup
        working-directory: src
        run: yarn install

      - name: Lint
        working-directory: src
        run: yarn lint

      - name: Build
        working-directory: src
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: yarn build

      - name: Release
        working-directory: src/scripts
        continue-on-error: true
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          DREAMLINK_TOKEN: ${{ secrets.DREAMLINK_TOKEN }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REF: ${{ github.ref }}
          BUILD_OS: ${{ matrix.os-short }}
          BUILD_OS_EXTENSION: ${{ matrix.os-extension }}
        run: node release.js
